site_name: Reloaded II Documentation
site_url: https://reloaded-project.github.io/Reloaded-II/

repo_name: Reloaded-Project/Reloaded-II
repo_url: https://github.com/Reloaded-Project/Reloaded-II

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sewer56
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheSewer56

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: red
    accent: red
    scheme: slate
    
nav:
  - Home: index.md
  - For Users:
    - Quick Start: QuickStart.md
    - Frequently Asked Questions: FAQ.md
    - Advanced:
        - NuGet Sources: NuGetSources.md
        - Injection Methods: InjectionMethods.md
  - For Modders:
    - Getting Started: GettingStartedMods.md
    - Publishing Mods: PublishingMods.md
  - For Programmers:
    - Building Mods: BuildingMods.md
    - Dependency Injection: DependencyInjection.md
    - Miscellaneous:
        - Automation: Automation.md
        - API Overview: APIOverview.md
        - Optimizing Mods: OptimizingMods.md
        - Shared Libraries: https://github.com/Sewer56/Reloaded.SharedLib.Hooks
        - Writing Mods for Actively Developed Games/Apps: https://github.com/Sewer56/Reloaded.SharedLib.Hooks#supporting-actively-developed-applications
        - Writing Native Mods: NativeMods.md
        - Troubleshooting: Troubleshooting.md
        
  - For Contributors:
    - Building Reloaded: BuildingReloaded.md
    - Project Structure: ProjectStructure.md
    - High Level Architecture: Reloaded-II-Architecture.md
    - Translating Reloaded: LocalizingReloaded.md
    - Miscellaneous:
      - Reloaded vs Reloaded II: Reloaded-vs-Reloaded-II.md